#!/bin/bash

#What are conditionals?

#A conditonal checks if something is true or false then runs code based on the result

#How it works

#Conditonals are used inside brackets 
#if > starts the check
#then > begings the code block
#else > optional fallback
#fi ends the conditional






grade=95

if [ "$grade" -ge 90 ]; then
  echo "W grade"
elif [ "$grade" -gt 70 ] && [ "$grade" -lt 80 ]; then
  echo "atleast push for an 80 gang"
else
  echo "Chai"
fi

